config/routes.rb
BootstrapAndRails::Application.routes.draw do
  
  get "home/index"
  resources :events

    get "events/index"

  resource :calendar, only: [:show], controller: :calendar
  root to: "calendar#show"

end

app/models/event.rb
class Event < ActiveRecord::Base
	validates :startdate, :enddate, :createtime, :place, :title, presence: true
	#validates :place, presence: true
	#validates :startdate, presence: true
	#validates :enddate, presence: true
	#validates :createtime, presence: true

validate :date_cannot_be_in_the_past
  def date_cannot_be_in_the_past
    errors.add(:startdate, "can't be earlier enddate") if
       startdate > enddate
  end
 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def show
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end
end

app/controllers/events_controller.rb
  class EventsController < ApplicationController
    before_action :set_event, only: [:show, :edit, :update, :destroy]

    # GET /events
    # GET /events.json
    def index
  #    @events = Event.where(startdate: params[:date]  )
      @events = Event.where('startdate BETWEEN ? AND ?', DateTime.parse(params[:date] + " 00:00:00" ), DateTime.parse(params[:date] + " 23:59:59" )).all
          @date = params[:date] # ? Date.parse(params[:date]) : Date.today



      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @events }
      end
    end

    # GET /events/1
    # GET /events/1.json
    def show

        @event = Event.find(params[:id])
        @date = Event.find(params[:id]).startdate.to_date
        
        respond_to do |format|
        format.html  #show.html.erb
        format.json { render json: @event }
      end



    end

    # GET /events/new
    def new
      @date = params[:date]
      @event = Event.new
      @event.startdate = DateTime.parse( params[:date] + " 00:00:00" );
      @event.enddate = DateTime.parse( params[:date] + " 00:00:00" );
      @today = DateTime.now

      respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end

    end

    # GET /events/1/edit
    def edit
    end

    # POST /events
    # POST /events.json
    def create
      @event = Event.new(event_params)

      respond_to do |format|

        if @event.save
          format.html { redirect_to @event, notice: 'Event was successfully created.' }
          format.json { render action: 'index', status: :created, location: @event }
        else
          format.html { render action: 'new' }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      end
    end




    # PATCH/PUT /events/1
    # PATCH/PUT /events/1.json
    def update

      respond_to do |format|
        if @event.update(event_params)
          format.html { redirect_to @event, notice: 'Event was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      end


    end

    # DELETE /events/1
    # DELETE /events/1.json
    def destroy
      @event.destroy
      respond_to do |format|
        format.html { redirect_to :back }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_event
        @event = Event.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def event_params
        params.require(:event).permit(:title, :place, :startdate, :enddate, :createtime)
      end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/calendar/show.html.erb
<div class="page-header">
  <h1>Calendar <small>sibext.com</small></h1>


  <div class="row">
    <div class="col-md-12 text-center">
      <div class="well controls">
        <div class="container">
          <div class="row row-centered">
            <div class="col-xs-6 col-centered">
              <%= link_to calendar_path(date: @date - 1.year), class: "btn btn-default" do %>
              <i class="glyphicon glyphicon-backward"></i>
              <% end %>
              <%= "#{@date.year}" %>
              <%= link_to calendar_path(date: @date + 1.year), class: "btn btn-default" do %>
              <i class="glyphicon glyphicon-forward"></i>
              <% end %>
            </div>
            <div class="col-xs-6 col-centered">
              <%= link_to calendar_path(date: @date - 1.month), class: "btn btn-default" do %>
              <i class="glyphicon glyphicon-backward"></i>
              <% end %>
              <%= "#{@date.strftime("%B")} " %>
              <%= link_to calendar_path(date: @date + 1.month), class: "btn btn-default" do %>
              <i class="glyphicon glyphicon-forward"></i>
              <% end %>

            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= calendar @date do |date| %>
      <%= if @date.month == date.month
           link_to date.day , events_path(date:date)
        end %>
      <% end %>
  </div>
</div>
</div>

app/views/calendar/show.html.haml
.page-header
  %h1
    Calendar
    %small sibext.com
  .row
    .col-md-12.text-center
      .well.controls
        .container
          .row.row-centered
            .col-xs-6.col-centered
              = link_to calendar_path(date: @date - 1.year), class: "btn btn-default" do
                %i.glyphicon.glyphicon-backward
              = "#{@date.year}"
              = link_to calendar_path(date: @date + 1.year), class: "btn btn-default" do
                %i.glyphicon.glyphicon-forward
            .col-xs-6.col-centered
              = link_to calendar_path(date: @date - 1.month), class: "btn btn-default" do
                %i.glyphicon.glyphicon-backward
              = "#{@date.strftime("%B")} "
              = link_to calendar_path(date: @date + 1.month), class: "btn btn-default" do
                %i.glyphicon.glyphicon-forward
  .row
    .col-md-12
      = calendar @date do |date|
        -if @date.month == date.month 
          =link_to date.day , events_path(date:date)

app/views/events/_event.html.erb
<li><%= event.title %></li>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :place %><br>
    <%= f.text_field :place %>
  </div>
  <div class="field">
    <%= f.label :startdate %><br>
    <%= f.datetime_select :startdate %>
  </div>
  <div class="field">
    <%= f.label :enddate %><br>
    <%= f.datetime_select :enddate %>
  </div>
  <div class="field">
    <%= f.label :createtime %><br>
    <%= f.datetime_select :createtime %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/_form.html.haml
= form_for(@event) do |f|
  - if @event.errors.any?
    #error_explanation
      %h2
        = pluralize(@event.errors.count, "error")
        prohibited this event from being saved:
      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :title
    %br/
    = f.text_field :title
  .field
    = f.label :place
    %br/
    = f.text_field :place
  .field
    = f.label :startdate
    %br/
    = f.datetime_select :startdate
  .field
    = f.label :enddate
    %br/
    = f.datetime_select :enddate
  .field
    = f.label :createtime
    %br/
    = f.datetime_select :createtime
  .actions
    = f.submit

app/views/events/create.js.erb
$("<%= escape_javascript(render @event) %>").appendTo("#events");

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/edit.html.haml
%h1 Editing event
= render 'form'
= link_to 'Show', @event
|
\#{link_to 'Back', events_path}

app/views/events/index.html.erb
<h1>Listing events</h1>

<div class="bs-example">
    <table class="table">
      <thead>
        <tr>
          <th>title</th>
          <th>place</th>
          <th>start date</th>
          <th>end date</th>
          <th>create date</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
            <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.place %></td>
        <td><%= event.startdate %></td>
        <td><%= event.enddate %></td>
        <td><%= event.createtime %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

      </tbody>
    </table>
  </div>



<br>

      <%= link_to 'New event' , new_event_path(date: @date)%>

<br>
      <%= link_to 'Back' , root_path %>

app/views/events/index.html.haml
%h1 Listing events
.bs-example
  %table.table
    %thead
      %tr
        %th title
        %th place
        %th start date
        %th end date
        %th create date
        %th
        %th
        %th
    %tbody
      - @events.each do |event|
        %tr
          %td= event.title
          %td= event.place
          %td= event.startdate
          %td= event.enddate
          %td= event.createtime
          %td= link_to 'Show', event
          %td= link_to 'Edit', edit_event_path(event)
          %td= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New event' , new_event_path(date: @date)
%br/
= link_to 'Back' , root_path

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/new.html.haml
:javascript
  $(document).ready(function(){
    $('#shit')
      .bind("ajax:beforeSend", function(evt, xhr, settings){
        var $submitButton = $(this).find('input[name="commit"]');
  
        // Update the text of the submit button to let the user know stuff is happening.
        // But first, store the original text of the submit button, so it can be restored when the request is finished.
        $submitButton.data( 'origText', $(this).text() );
        $submitButton.text( "Submitting..." );
  
      })
      .bind("ajax:success", function(evt, data, status, xhr){
      //  var $form = $(this);
  
  //ЧТО-ТО ВРОДЕ REDIRECT_TO!!!!!!!!
  
        // Reset fields and any validation errors, so form can be used again, but leave hidden_field values intact.
  //      $form.find('textarea,input[type="text"],input[type="file"]').val("");
    //    $form.find('div.validation-error').empty();
  
        // Insert response partial into page below the form.
        $('#comments').append(xhr.responseText);
  
      })
  });



%h1 New event

= form_for @event ,id: "shit", remote: true do |f|
  title: #{f.text_field :title}
  %br/
  place : #{f.text_field :place}
  %br/
  start date : #{f.datetime_field :startdate}
  %br/
  end date : #{f.datetime_field :enddate}
  %br/
  #{f.hidden_field :createtime, :value => @today}
  %br/

  = f.submit "commit" 

= link_to 'Back', events_path(date:@date)



app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Place:</strong>
  <%= @event.place %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @event.startdate %>
</p>

<p>
  <strong>Enddate:</strong>
  <%= @event.enddate %>
</p>

<p>
  <strong>Createtime:</strong>
  <%= @event.createtime %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path(date: @date) %>

app/views/events/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @event.title
%p
  %strong Place:
  = @event.place
%p
  %strong Startdate:
  = @event.startdate
%p
  %strong Enddate:
  = @event.enddate
= link_to 'Edit', edit_event_path(@event)
= link_to 'Back', events_path(date: @date)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CalendarExample</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "http://yandex.st/bootstrap/3.0.2/css/bootstrap.min.css", media: "all" %>
  <%= javascript_include_tag "http://yandex.st/bootstrap/3.0.2/js/bootstrap.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<%= yield %>
</div>

</body>
</html>